const LOGOS_2026 = {
  redbull: "images/cars/redbull.avif",
  ferrari: "images/cars/ferrari.avif",
  mclaren: "images/cars/mclaren.avif",
  mercedes: "images/cars/mercedes.avif",
  aston: "images/cars/astonmartin.avif",
  alpine: "images/cars/alpine.avif",
  williams: "images/cars/williams.avif",
  racingbulls: "images/cars/racingbulls.avif",
  audi: "images/cars/audi.avif",
  haas: "images/cars/haas.avif",
  cadillac: "images/cars/cadillac.avif",
};

export const drivers = [
  {
    name: "Max Verstappen",
    team: "Red Bull",
    number: "3",
    country: "nl",
    color: "#3671C6",
    carImg: LOGOS_2026.redbull,
    driverImg: "images/drivers/ver.avif",
  },
  {
    name: "Isack Hadjar",
    team: "Red Bull",
    number: "43",
    country: "fr",
    color: "#3671C6",
    carImg: LOGOS_2026.redbull,
    driverImg: "images/drivers/had.avif",
  },
  {
    name: "Lewis Hamilton",
    team: "Ferrari",
    number: "44",
    country: "gb",
    color: "#E80020",
    carImg: LOGOS_2026.ferrari,
    driverImg: "images/drivers/ham.avif",
  },
  {
    name: "Charles Leclerc",
    team: "Ferrari",
    number: "16",
    country: "mc",
    color: "#E80020",
    carImg: LOGOS_2026.ferrari,
    driverImg: "images/drivers/lec.avif",
  },
  {
    name: "Lando Norris",
    team: "McLaren",
    number: "1",
    country: "gb",
    color: "#FF8000",
    carImg: LOGOS_2026.mclaren,
    driverImg: "images/drivers/nor.avif",
  },
  {
    name: "Oscar Piastri",
    team: "McLaren",
    number: "81",
    country: "au",
    color: "#FF8000",
    carImg: LOGOS_2026.mclaren,
    driverImg: "images/drivers/pia.avif",
  },
  {
    name: "George Russell",
    team: "Mercedes",
    number: "63",
    country: "gb",
    color: "#27CCB4",
    carImg: LOGOS_2026.mercedes,
    driverImg: "images/drivers/rus.avif",
  },
  {
    name: "Kimi Antonelli",
    team: "Mercedes",
    number: "12",
    country: "it",
    color: "#27CCB4",
    carImg: LOGOS_2026.mercedes,
    driverImg: "images/drivers/ant.avif",
  },
  {
    name: "Fernando Alonso",
    team: "Aston Martin",
    number: "14",
    country: "es",
    color: "#229971",
    carImg: LOGOS_2026.aston,
    driverImg: "images/drivers/alo.avif",
  },
  {
    name: "Lance Stroll",
    team: "Aston Martin",
    number: "18",
    country: "ca",
    color: "#229971",
    carImg: LOGOS_2026.aston,
    driverImg: "images/drivers/str.avif",
  },
  {
    name: "Pierre Gasly",
    team: "Alpine",
    number: "10",
    country: "fr",
    color: "#0093CC",
    carImg: LOGOS_2026.alpine,
    driverImg: "images/drivers/gas.avif",
  },
  {
    name: "Franco Colapinto",
    team: "Alpine",
    number: "43",
    country: "ar",
    color: "#0093CC",
    carImg: LOGOS_2026.alpine,
    driverImg: "images/drivers/col.avif",
  },
  {
    name: "Carlos Sainz",
    team: "Williams",
    number: "55",
    country: "es",
    color: "#37BEDD",
    carImg: LOGOS_2026.williams,
    driverImg: "images/drivers/sai.avif",
  },
  {
    name: "Alex Albon",
    team: "Williams",
    number: "23",
    country: "th",
    color: "#37BEDD",
    carImg: LOGOS_2026.williams,
    driverImg: "images/drivers/alb.avif",
  },
  {
    name: "Liam Lawson",
    team: "Racing Bulls",
    number: "30",
    country: "nz",
    color: "#6692FF",
    carImg: LOGOS_2026.racingbulls,
    driverImg: "images/drivers/law.avif",
  },
  {
    name: "Arvid Lindblad",
    team: "Racing Bulls",
    number: "40",
    country: "gb",
    color: "#6692FF",
    carImg: LOGOS_2026.racingbulls,
    driverImg: "images/drivers/lin.avif",
  },
  {
    name: "Nico Hülkenberg",
    team: "Audi",
    number: "27",
    country: "de",
    color: "#00E6C3",
    carImg: LOGOS_2026.audi,
    driverImg: "images/drivers/hul.avif",
  },
  {
    name: "Gabriel Bortoleto",
    team: "Audi",
    number: "5",
    country: "br",
    color: "#00E6C3",
    carImg: LOGOS_2026.audi,
    driverImg: "images/drivers/bor.avif",
  },
  {
    name: "Oliver Bearman",
    team: "Haas",
    number: "87",
    country: "gb",
    color: "#B6BABD",
    carImg: LOGOS_2026.haas,
    driverImg: "images/drivers/bea.avif",
  },
  {
    name: "Esteban Ocon",
    team: "Haas",
    number: "31",
    country: "fr",
    color: "#B6BABD",
    carImg: LOGOS_2026.haas,
    driverImg: "images/drivers/oco.avif",
  },
  {
    name: "Valtteri Bottas",
    team: "Cadillac",
    number: "77",
    country: "fi",
    color: "#900C3F",
    carImg: LOGOS_2026.cadillac,
    driverImg: "images/drivers/bot.avif",
  },
  {
    name: "Sergio Pérez",
    team: "Cadillac",
    number: "11",
    country: "mx",
    color: "#900C3F",
    carImg: LOGOS_2026.cadillac,
    driverImg: "images/drivers/per.avif",
  },
];
