name: Calcul Automatique des Points F1

on:
  schedule:
    # S'exécute tous les jours à 7h00 du matin (Heure de Paris)
    - cron: '0 5 * * *'
  workflow_dispatch: # Te permet aussi de lancer le calcul à la main si besoin depuis GitHub !

jobs:
  calculer:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # 🛠️ Corrigé et configuré sur Node 24 pour effacer le warning

      - name: Installer les dépendances (Firebase & Axios)
        run: npm install firebase-admin axios

      - name: Lancer le script de calcul des scores
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node cron-calcul.js
